# Generated by Django 3.2.3 on 2021-11-17 14:45

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('is_male', models.BooleanField()),
                ('car_brand', models.CharField(max_length=50)),
                ('car_type', models.CharField(max_length=50)),
                ('battery_range', models.PositiveIntegerField(validators=[home.models.Member.validate_battery_range])),
                ('has_card', models.BooleanField(default=False)),
                ('license', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
