# Generated by Django 3.2.3 on 2021-12-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_member_id_alter_member_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('image', models.ImageField(upload_to='images/product')),
                ('name', models.CharField(default='Not Working', max_length=50, null=True)),
                ('description', models.CharField(max_length=400)),
                ('socket_type', models.CharField(max_length=50)),
                ('number_of_sockets', models.IntegerField()),
                ('charging_power', models.IntegerField()),
                ('protection', models.CharField(max_length=100)),
                ('ware_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='license',
            field=models.ImageField(upload_to='images/license'),
        ),
    ]
